[package]
name = "doubly-linked-list"
version = "0.0.0"
edition = "2021"

[features]
default = ["advanced"]

# check correct covariance and Send, Sync
advanced = []

[lints.clippy]
new_without_default = "allow"
